name: Docker Image CI
on:
  push:
    branches: [ "openwrt-18.06" ]
  pull_request:
    branches: [ "openwrt-18.06" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      FROM: ubuntu:18.04
      env: DEBIAN_FRONTEND = noninteractive
      run: "apt-get update && apt-get install -y  build-essential  vim  git wget rsync curl time subversion libncurses5-dev zlib1g-dev gawk flex quilt git-core unzip libssl-dev python-dev python-pip  libxml-parser-perl default-jdk"
      ENV: FORCE_UNSAFE_CONFIGURE 1
      copy: . /root/source
      WORKDIR: /root/source
      RUN: "sh scripts/onion-feed-setup.sh && python scripts/onion-setup-build.py"
